/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

#include <stdint.h>
#include <stdlib.h>
#include <lcm/lcm_coretypes.h>
#include <lcm/lcm.h>

#ifndef _gripper_lcm_t_h
#define _gripper_lcm_t_h

#ifdef __cplusplus
extern "C" {
#endif

typedef struct _gripper_lcm_t gripper_lcm_t;
struct _gripper_lcm_t
{
    int8_t     left_closed;
    int8_t     right_closed;
};

gripper_lcm_t   *gripper_lcm_t_copy(const gripper_lcm_t *p);
void gripper_lcm_t_destroy(gripper_lcm_t *p);

typedef struct _gripper_lcm_t_subscription_t gripper_lcm_t_subscription_t;
typedef void(*gripper_lcm_t_handler_t)(const lcm_recv_buf_t *rbuf,
             const char *channel, const gripper_lcm_t *msg, void *user);

int gripper_lcm_t_publish(lcm_t *lcm, const char *channel, const gripper_lcm_t *p);
gripper_lcm_t_subscription_t* gripper_lcm_t_subscribe(lcm_t *lcm, const char *channel, gripper_lcm_t_handler_t f, void *userdata);
int gripper_lcm_t_unsubscribe(lcm_t *lcm, gripper_lcm_t_subscription_t* hid);
int gripper_lcm_t_subscription_set_queue_capacity(gripper_lcm_t_subscription_t* subs,
                              int num_messages);


int  gripper_lcm_t_encode(void *buf, int offset, int maxlen, const gripper_lcm_t *p);
int  gripper_lcm_t_decode(const void *buf, int offset, int maxlen, gripper_lcm_t *p);
int  gripper_lcm_t_decode_cleanup(gripper_lcm_t *p);
int  gripper_lcm_t_encoded_size(const gripper_lcm_t *p);

// LCM support functions. Users should not call these
int64_t __gripper_lcm_t_get_hash(void);
int64_t __gripper_lcm_t_hash_recursive(const __lcm_hash_ptr *p);
int     __gripper_lcm_t_encode_array(void *buf, int offset, int maxlen, const gripper_lcm_t *p, int elements);
int     __gripper_lcm_t_decode_array(const void *buf, int offset, int maxlen, gripper_lcm_t *p, int elements);
int     __gripper_lcm_t_decode_array_cleanup(gripper_lcm_t *p, int elements);
int     __gripper_lcm_t_encoded_array_size(const gripper_lcm_t *p, int elements);
int     __gripper_lcm_t_clone_array(const gripper_lcm_t *p, gripper_lcm_t *q, int elements);

#ifdef __cplusplus
}
#endif

#endif
