/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

#include <string.h>
#include "gripper_lcm_t.h"

static int __gripper_lcm_t_hash_computed;
static int64_t __gripper_lcm_t_hash;

int64_t __gripper_lcm_t_hash_recursive(const __lcm_hash_ptr *p)
{
    const __lcm_hash_ptr *fp;
    for (fp = p; fp != NULL; fp = fp->parent)
        if (fp->v == __gripper_lcm_t_get_hash)
            return 0;

    __lcm_hash_ptr cp;
    cp.parent =  p;
    cp.v = (void*)__gripper_lcm_t_get_hash;
    (void) cp;

    int64_t hash = 0x38fc580a6162a246LL
         + __int8_t_hash_recursive(&cp)
         + __int8_t_hash_recursive(&cp)
        ;

    return (hash<<1) + ((hash>>63)&1);
}

int64_t __gripper_lcm_t_get_hash(void)
{
    if (!__gripper_lcm_t_hash_computed) {
        __gripper_lcm_t_hash = __gripper_lcm_t_hash_recursive(NULL);
        __gripper_lcm_t_hash_computed = 1;
    }

    return __gripper_lcm_t_hash;
}

int __gripper_lcm_t_encode_array(void *buf, int offset, int maxlen, const gripper_lcm_t *p, int elements)
{
    int pos = 0, thislen, element;

    for (element = 0; element < elements; element++) {

        thislen = __int8_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].left_closed), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int8_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].right_closed), 1);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int gripper_lcm_t_encode(void *buf, int offset, int maxlen, const gripper_lcm_t *p)
{
    int pos = 0, thislen;
    int64_t hash = __gripper_lcm_t_get_hash();

    thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    thislen = __gripper_lcm_t_encode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int __gripper_lcm_t_encoded_array_size(const gripper_lcm_t *p, int elements)
{
    int size = 0, element;
    for (element = 0; element < elements; element++) {

        size += __int8_t_encoded_array_size(&(p[element].left_closed), 1);

        size += __int8_t_encoded_array_size(&(p[element].right_closed), 1);

    }
    return size;
}

int gripper_lcm_t_encoded_size(const gripper_lcm_t *p)
{
    return 8 + __gripper_lcm_t_encoded_array_size(p, 1);
}

int __gripper_lcm_t_decode_array(const void *buf, int offset, int maxlen, gripper_lcm_t *p, int elements)
{
    int pos = 0, thislen, element;

    for (element = 0; element < elements; element++) {

        thislen = __int8_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].left_closed), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int8_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].right_closed), 1);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int __gripper_lcm_t_decode_array_cleanup(gripper_lcm_t *p, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __int8_t_decode_array_cleanup(&(p[element].left_closed), 1);

        __int8_t_decode_array_cleanup(&(p[element].right_closed), 1);

    }
    return 0;
}

int gripper_lcm_t_decode(const void *buf, int offset, int maxlen, gripper_lcm_t *p)
{
    int pos = 0, thislen;
    int64_t hash = __gripper_lcm_t_get_hash();

    int64_t this_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (this_hash != hash) return -1;

    thislen = __gripper_lcm_t_decode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int gripper_lcm_t_decode_cleanup(gripper_lcm_t *p)
{
    return __gripper_lcm_t_decode_array_cleanup(p, 1);
}

int __gripper_lcm_t_clone_array(const gripper_lcm_t *p, gripper_lcm_t *q, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __int8_t_clone_array(&(p[element].left_closed), &(q[element].left_closed), 1);

        __int8_t_clone_array(&(p[element].right_closed), &(q[element].right_closed), 1);

    }
    return 0;
}

gripper_lcm_t *gripper_lcm_t_copy(const gripper_lcm_t *p)
{
    gripper_lcm_t *q = (gripper_lcm_t*) malloc(sizeof(gripper_lcm_t));
    __gripper_lcm_t_clone_array(p, q, 1);
    return q;
}

void gripper_lcm_t_destroy(gripper_lcm_t *p)
{
    __gripper_lcm_t_decode_array_cleanup(p, 1);
    free(p);
}

int gripper_lcm_t_publish(lcm_t *lc, const char *channel, const gripper_lcm_t *p)
{
      int max_data_size = gripper_lcm_t_encoded_size (p);
      uint8_t *buf = (uint8_t*) malloc (max_data_size);
      if (!buf) return -1;
      int data_size = gripper_lcm_t_encode (buf, 0, max_data_size, p);
      if (data_size < 0) {
          free (buf);
          return data_size;
      }
      int status = lcm_publish (lc, channel, buf, data_size);
      free (buf);
      return status;
}

struct _gripper_lcm_t_subscription_t {
    gripper_lcm_t_handler_t user_handler;
    void *userdata;
    lcm_subscription_t *lc_h;
};
static
void gripper_lcm_t_handler_stub (const lcm_recv_buf_t *rbuf,
                            const char *channel, void *userdata)
{
    int status;
    gripper_lcm_t p;
    memset(&p, 0, sizeof(gripper_lcm_t));
    status = gripper_lcm_t_decode (rbuf->data, 0, rbuf->data_size, &p);
    if (status < 0) {
        fprintf (stderr, "error %d decoding gripper_lcm_t!!!\n", status);
        return;
    }

    gripper_lcm_t_subscription_t *h = (gripper_lcm_t_subscription_t*) userdata;
    h->user_handler (rbuf, channel, &p, h->userdata);

    gripper_lcm_t_decode_cleanup (&p);
}

gripper_lcm_t_subscription_t* gripper_lcm_t_subscribe (lcm_t *lcm,
                    const char *channel,
                    gripper_lcm_t_handler_t f, void *userdata)
{
    gripper_lcm_t_subscription_t *n = (gripper_lcm_t_subscription_t*)
                       malloc(sizeof(gripper_lcm_t_subscription_t));
    n->user_handler = f;
    n->userdata = userdata;
    n->lc_h = lcm_subscribe (lcm, channel,
                                 gripper_lcm_t_handler_stub, n);
    if (n->lc_h == NULL) {
        fprintf (stderr,"couldn't reg gripper_lcm_t LCM handler!\n");
        free (n);
        return NULL;
    }
    return n;
}

int gripper_lcm_t_subscription_set_queue_capacity (gripper_lcm_t_subscription_t* subs,
                              int num_messages)
{
    return lcm_subscription_set_queue_capacity (subs->lc_h, num_messages);
}

int gripper_lcm_t_unsubscribe(lcm_t *lcm, gripper_lcm_t_subscription_t* hid)
{
    int status = lcm_unsubscribe (lcm, hid->lc_h);
    if (0 != status) {
        fprintf(stderr,
           "couldn't unsubscribe gripper_lcm_t_handler %p!\n", hid);
        return -1;
    }
    free (hid);
    return 0;
}

